import javax.swing.*;

import java.awt.event.*;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.util.Objects;

import static javax.swing.SwingUtilities.updateComponentTreeUI;

/**
 *
 * @author Yann
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws Exception {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            updateComponentTreeUI(this);
        }
        catch(Exception e) {
            System.out.println("Look and Feel Windows indisponible");
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jButton1.setText("Séléctionner un fichier");
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getUserFile();
            }
        });
        jPanel2.add(jButton1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aucun fichier choisi");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jPanel5.setLayout(new java.awt.GridLayout());

        jTextField1.setText("Entrez la clé de cryptage (int)");
        jTextField1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Main.mode = "single";
                Main.singleInit = Long.parseLong(jTextField1.getText());
                JOptionPane.showMessageDialog(null, "Valeur définie");
            }
        });

        jTextField1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                System.out.println("gained focus");
                if (Objects.equals(jTextField1.getText(), "Entrez la clé de cryptage (int)")) {
                    jTextField1.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (Objects.equals(jTextField1.getText(), "")) {
                    jTextField1.setText("Entrez la clé de cryptage (int)");
                }
            }
        });
        jPanel5.add(jTextField1);

        jTabbedPane1.addTab("Simple", jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(4, 0));

        jTextField2.setText("Entrez la clé 1");
        jTextField2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Main.mode = "multi";
                Main.vnInit = Long.parseLong(jTextField2.getText());
                JOptionPane.showMessageDialog(null, "Valeur définie");
            }
        });
        jTextField2.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (Objects.equals(jTextField2.getText(), "Entrez la clé 1")) {
                    jTextField2.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (Objects.equals(jTextField2.getText(), "")) {
                    jTextField2.setText("Entrez la clé 1");
                }
            }
        });
        jPanel6.add(jTextField2);

        jTextField3.setText("Entrez la clé 2");
        jTextField3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Main.mode = "multi";
                Main.xnInit = Long.parseLong(jTextField3.getText());
                JOptionPane.showMessageDialog(null, "Valeur définie");
            }
        });
        jTextField3.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (Objects.equals(jTextField3.getText(), "Entrez la clé 2")) {
                    jTextField3.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (Objects.equals(jTextField3.getText(), "")) {
                    jTextField3.setText("Entrez la clé 2");
                }
            }
        });
        jPanel6.add(jTextField3);

        jTextField4.setText("Entrez la clé 3");
        jTextField4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Main.mode = "multi";
                Main.ynInit = Long.parseLong(jTextField4.getText());
                JOptionPane.showMessageDialog(null, "Valeur définie");
            }
        });
        jTextField4.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (Objects.equals(jTextField4.getText(), "Entrez la clé 3")){
                    jTextField4.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (Objects.equals(jTextField4.getText(), "")) {
                    jTextField4.setText("Entrez la clé 3");
                }
            }
        });
        jPanel6.add(jTextField4);

        jTextField5.setText("Entrez la clé 4");
        jTextField5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Main.mode = "multi";
                Main.znInit = Long.parseLong(jTextField5.getText());
                JOptionPane.showMessageDialog(null, "Valeur définie");
            }
        });
        jTextField5.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (Objects.equals(jTextField5.getText(), "Entrez la clé 4")) {
                    jTextField5.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (Objects.equals(jTextField5.getText(), "")) {
                    jTextField5.setText("Entrez la clé 4");
                }
            }
        });
        jPanel6.add(jTextField5);

        jTabbedPane1.addTab("Multiple", jPanel6);

        jPanel3.add(jTabbedPane1);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout());

        jButton2.setText("Crypter");
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    Main.process();
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
        jPanel4.add(jButton2);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Fichier");

        jMenuItem1.setText("Choisir un fichier");
        jMenuItem2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getUserFile();
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>

    public void getUserFile() {
        JFileChooser fileChooser = new JFileChooser();
        int response = fileChooser.showOpenDialog(null);
        if (response == JFileChooser.APPROVE_OPTION) {
            Main.inputPath = fileChooser.getSelectedFile().toPath();
            jLabel1.setText(Main.inputPath.toString());

        }
    }



    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration
}
